server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: banking-account-service

  # API Versioning (Spring Boot 4)
  mvc:
    api-version:
      # Obliga a que todas las peticiones incluyan una versión.
      # Si el cliente no la envía, la solicitud fallará (generalmente con un 400 Bad Request).
      required: true

      # Define qué versiones son válidas en tu aplicación.
      # En este caso, solo aceptará peticiones marcadas como versión 1 o 2.
      supported: 1,2
      use:
        # Indica que la versión se debe extraer de un segmento de la ruta (URL).
        # El valor 0 es el índice del segmento de ruta donde se espera la versión. Por ejemplo:
        # Para una estructura de URL como /{versión}/resource, use 0.
        # Para una estructura de URL como /api/{versión}/resource, use 1.
        path-segment: 1

  datasource:
    url: jdbc:postgresql://localhost:5435/db_hexagonal
    username: magadiflo
    password: magadiflo

  jpa:
    hibernate:
      ddl-auto: validate    # validate: hibernate solo valida el schema, Flyway es quien lo crea
    properties:
      hibernate:
        format_sql: true

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    baseline-description: 'init'
    baseline-version: 0

# ===== Configuración personalizada del servicio externo (ExchangeRate API) =====
exchange-rate:
  api:
    base-url: https://v6.exchangerate-api.com/v6
    api-key: 8e2e421bfc44c2a3c72ef218
    timeout-seconds: 5

logging:
  level:
    dev.magadiflo: debug
    org.hibernate.SQL: debug
    org.flywaydb: info
